foreach(_required CLI VALIDATOR PROFILES DESTINATION)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "Missing asset generation argument: ${_required}")
    endif()
endforeach()
file(READ "${PROFILES}/export/ringqueen.json" _export)
string(JSON _manifest_name GET "${_export}" manifest_json)
if(NOT _manifest_name MATCHES "^[A-Za-z0-9_-]+\\.json$")
    message(FATAL_ERROR "Unsafe manifest filename")
endif()
if(VALIDATE_ONLY)
    set(_output "${DESTINATION}")
else()
    if(NOT EXISTS "${INPUT}")
        message(FATAL_ERROR "Missing neutral boxer: ${INPUT}")
    endif()
    set(_output "${DESTINATION}.staging")
    file(REMOVE_RECURSE "${_output}")
endif()

function(run_asset_step)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    if(NOT _result EQUAL 0)
        if(NOT VALIDATE_ONLY)
            file(REMOVE_RECURSE "${_output}")
        endif()
        message(FATAL_ERROR "RingQueen asset validation/generation failed (${_result}):\n${_stdout}\n${_stderr}")
    endif()
endfunction()

if(NOT VALIDATE_ONLY)
    run_asset_step("${CLI}" generate --input "${INPUT}" --out "${_output}"
        --rig-profile "${PROFILES}/rig/boxer_default.json" --motion-dir "${PROFILES}/motion"
        --palette-profile "${PROFILES}/palette/boxer_default.json" --export-profile "${PROFILES}/export/ringqueen.json")
endif()
run_asset_step("${CLI}" rig-validate --rig "${_output}/rig.json" --rig-profile "${PROFILES}/rig/boxer_default.json")
run_asset_step("${CLI}" audit --input "${_output}" --rig-profile "${PROFILES}/rig/boxer_default.json"
    --palette-profile "${PROFILES}/palette/boxer_default.json" --export-profile "${PROFILES}/export/ringqueen.json")
run_asset_step("${VALIDATOR}" "${_output}/${_manifest_name}")
if(NOT VALIDATE_ONLY)
    file(REMOVE_RECURSE "${DESTINATION}")
    file(RENAME "${_output}" "${DESTINATION}")
endif()