function(build_engine expected_success)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BUILD_DIR}" --target ringqueen-engine --config "${CONFIG}" --parallel 2
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    set(BUILD_OUTPUT "${_stdout}\n${_stderr}" PARENT_SCOPE)
    if(expected_success AND NOT _result EQUAL 0)
        message(FATAL_ERROR "Engine build failed: ${_stdout}\n${_stderr}")
    elseif(NOT expected_success AND _result EQUAL 0)
        message(FATAL_ERROR "Engine build accepted invalid assets")
    endif()
endfunction()

build_engine(TRUE)
file(SHA256 "${ASSET_DIR}/${ATLAS_PNG}" _png_before)
file(SHA256 "${ASSET_DIR}/${MANIFEST_JSON}" _metadata_before)
build_engine(TRUE)
if(BUILD_OUTPUT MATCHES "Generating RingQueen sprite assets")
    message(FATAL_ERROR "No-op build regenerated assets")
endif()

file(READ "${ASSET_DIR}/${MANIFEST_JSON}" _manifest)
string(JSON _invalid SET "${_manifest}" schema_version 2)
file(WRITE "${ASSET_DIR}/${MANIFEST_JSON}" "${_invalid}")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BUILD_DIR}" --target ringqueen-engine --config "${CONFIG}" --parallel 2
    RESULT_VARIABLE _invalid_result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
file(WRITE "${ASSET_DIR}/${MANIFEST_JSON}" "${_manifest}")
if(_invalid_result EQUAL 0 OR NOT "${_stdout}\n${_stderr}" MATCHES "RingQueen asset validation/generation failed")
    message(FATAL_ERROR "Corrupt assets did not fail engine validation: ${_stdout}\n${_stderr}")
endif()
build_engine(TRUE)

file(REMOVE "${ASSET_DIR}/${ATLAS_PNG}")
execute_process(COMMAND "${VALIDATOR}" "${ASSET_DIR}/${MANIFEST_JSON}" RESULT_VARIABLE _missing_result OUTPUT_QUIET ERROR_QUIET)
if(_missing_result EQUAL 0)
    message(FATAL_ERROR "Runtime validator accepted a missing atlas")
endif()
build_engine(TRUE)
file(SHA256 "${ASSET_DIR}/${ATLAS_PNG}" _png_after)
file(SHA256 "${ASSET_DIR}/${MANIFEST_JSON}" _metadata_after)
if(NOT _png_before STREQUAL _png_after OR NOT _metadata_before STREQUAL _metadata_after)
    message(FATAL_ERROR "Regenerated assets differ from original build")
endif()

set(_bad_input "${BUILD_DIR}/invalid-neutral-boxer.png")
file(WRITE "${_bad_input}" "not a PNG")
foreach(_input "${_bad_input}" "${_bad_input}.missing")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCLI=${CLI}" "-DVALIDATOR=${VALIDATOR}" "-DPROFILES=${PROFILES}"
        "-DINPUT=${_input}" "-DDESTINATION=${ASSET_DIR}" -P "${GENERATE_SCRIPT}"
        RESULT_VARIABLE _bad_result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    if(_bad_result EQUAL 0)
        file(REMOVE "${_bad_input}")
        message(FATAL_ERROR "Invalid or missing source accepted")
    endif()
    file(SHA256 "${ASSET_DIR}/${MANIFEST_JSON}" _preserved)
    if(NOT _preserved STREQUAL _metadata_before)
        message(FATAL_ERROR "Failed generation replaced valid published assets")
    endif()
endforeach()
file(REMOVE "${_bad_input}")